added response & error handling
ubclaunchpad/pinpoint pull request #109
Opened 2018-12-14 23:55 UTC by adesouky

:tickets: **Ticket(s)**: Closes #100

---

## :construction_worker: Changes

Added response and error handling

## :flashlight: Testing Instructions

Go to client folder, run npm test

2018-12-15 00:07 UTC, bobheadxi requested changes
awesome stuff 😍 

linter errors reported by travis, however: https://travis-ci.com/ubclaunchpad/pinpoint/jobs/165334282#L464

2018-12-15 00:07 UTC, bobheadxi commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
this might be okay for now, but maybe we want something a little more structured, like:

```js
const STATUS_UNAUTHORIZED = "user unauthorized"


// ....

catch (error) {
    switch (error.response.status) {
        case 400:
            throw StatusUnauthorized;
    }
}
```

then, your test assertion might be:

```js
    .catch(err => {
      expect(err).toEqual(api.STATUS_UNAUTHORIZED);
```

2018-12-15 00:07 UTC, bobheadxi commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
wonder if anyone else has thoughts on this - maybe @leesw98 ?

2018-12-15 00:10 UTC, adesouky commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
Hmm, that makes sense, but since as of now we dont really know what errors/error codes t=our backend will return for most of the routes, can we even do that now?

2018-12-15 00:11 UTC, bobheadxi commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
thats true, so for now i guess maybe just set this up as a switch case with no real switches (just a default)

2018-12-15 00:11 UTC, adesouky commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
Also, any recommendations for JS linters for VS code. The one I'm using currently obviously isnt optimal.

2018-12-15 00:13 UTC, bobheadxi commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
I use this one: https://marketplace.visualstudio.com/items\?itemName\=dbaeumer.vscode-eslint

2018-12-15 13:20 UTC, adesouky commented on client/lib/api/index.js
> +    throw "error " + error.response.status;
Its great. Thanks!

2018-12-15 19:35 UTC, bobheadxi requested changes
Awesome, thanks for making the changes! Just one thing and I think this is good to go 🚀

2018-12-15 19:35 UTC, bobheadxi commented on client/lib/api/index.js
> +    } catch (error) {
These should be:

```suggestion
    } catch (error.response.status) {
```

2018-12-15 19:37 UTC, adesouky commented on client/lib/api/index.js
> +    } catch (error) {
Oh you mean the switch not the catch right?

2018-12-15 19:38 UTC, bobheadxi commented on client/lib/api/index.js
> +    } catch (error) {
Oh wait yes my bad, mobile phone reviews 😅

2018-12-15 19:40 UTC, adesouky commented on client/lib/api/index.js
> +    } catch (error) {
Haha, just changed it 😆

2018-12-15 19:40 UTC, bobheadxi approved these changes
Fantastic work, thanks @adesouky !

If you don’t mind, let’s wait a bit to get @leesw98 ‘s input before we merge?

2018-12-16 06:12 UTC, bwdmonkey approved these changes
LGTM for now. Might be worth something to investigate a better wrapper around these error reportings in the future.

2018-12-16 07:14 UTC, merged