frontend: application period creation page
ubclaunchpad/pinpoint pull request #115
Opened 2019-01-06 00:26 UTC by zhulia96

:tickets: **Ticket(s)**: Closes #111

---

## :construction_worker: Changes

Add application page under scenes

## :flashlight: Testing Instructions

Ran web app and saw the changes

2019-01-06 02:35 UTC, bobheadxi reviewed
great start! just a few tweaks needed 😁 thanks!

2019-01-06 02:35 UTC, bobheadxi commented on frontend/src/components/App.js
> +          <Route exact path="/scenes/applicationperiod" component={ApplicationPeriod} />
oh oops forgot to tell you, the routes are here:

https://github.com/ubclaunchpad/pinpoint/wiki/Frontend

But since we haven't really figured out how to do this yet, oh well

2019-01-06 02:35 UTC, bobheadxi commented on frontend/src/components/App.js
> +import ApplicationPeriod from '../scenes/ApplicationPeriod';
can you move this component to:

```
../scenes/ApplicationPeriod/create
```

since we'll have other `ApplicationPeriod` pages too later on, and this one is just for creating a new period

2019-01-09 04:37 UTC, leesw98 commented on frontend/src/scenes/ApplicationPeriod.js
> +    this.setState({
Some small things:
1. Reinforcing start date being before or equal to end date
2. Perhaps not allowing past dates to be selected (thoughts? @bobheadxi)

2019-01-09 04:37 UTC, leesw98 commented on frontend/src/scenes/ApplicationPeriod.js
> +    console.log(application);
Not sure what this function is for beyond setting value in the state. Are there reasons beyond this?

2019-01-09 04:37 UTC, leesw98 commented on frontend/src/scenes/ApplicationPeriod.js
> +    console.log(application);
Please remove the `console.log` as well.

2019-01-09 04:52 UTC, bobheadxi commented on frontend/src/scenes/ApplicationPeriod.js
> +    this.setState({
1. definitely
2. hm yeah sure this might be a good idea

2019-01-09 04:54 UTC, bobheadxi commented on frontend/src/scenes/ApplicationPeriod.js
> +    console.log(application);
Could probably do with more clarity, but it's used here: https://github.com/ubclaunchpad/pinpoint/pull/115/files/b34a2b0cc2d1bce5b7707925d10e35d3453e6e5b#diff-a539c042bc1a6e660ce83a6ecda93955R49

but yeah, I think it's just setting some form value in state? @zhulia96 can you elaborate?

also, this should be camelcased as `updateTextFields`

2019-01-12 22:22 UTC, LynxHack submitted a review, later dismissed
camelcase ;)

2019-01-12 22:26 UTC, bobheadxi requested changes
nice work~~~~~

2019-01-12 22:35 UTC, bobheadxi commented on frontend/src/styles/base/typography.scss
> +.heading1 {
the standard way to name this is `h1`

2019-01-12 22:36 UTC, bobheadxi commented on frontend/src/scenes/ApplicationPeriod/create.js
> +  updateTextFields(e) {
it looks like you renamed this without renaming usages of this?

2019-01-12 22:38 UTC, zhulia96 commented on frontend/src/scenes/ApplicationPeriod/create.js
> +  updateTextFields(e) {
The usages are already named properly

2019-01-12 23:24 UTC, bwdmonkey approved these changes

2019-01-12 23:41 UTC, bobheadxi approved these changes
awesome work, thanks! 😍

2019-01-12 23:41 UTC, merged