#122 add user info to database
ubclaunchpad/pinpoint pull request #125
Opened 2019-02-03 02:08 UTC by zhulia96

:tickets: **Ticket(s)**: Closes #122

---

## :construction_worker: Changes
linked sign up button to create account using the API 

## :flashlight: Testing Instructions
checked network activity in console

2019-02-03 02:18 UTC, leesw98 commented
Unsure why Travis build is failing. Will have to investigate

2019-02-03 02:48 UTC, bobheadxi reviewed
this should work - pending test check 😄

2019-02-04 08:37 UTC, bobheadxi commented
@srijonsaha you'll want to update this branch to include #126

2019-02-12 04:53 UTC, bobheadxi requested changes

2019-02-12 04:53 UTC, bobheadxi commented on gateway/api/user/user_test.go
> +		}}, errs{true}, http.StatusInternalServerError},
we have several error cases right? maybe make `createUserFail` an `error` instead of a `bool`, and we can test the specific error cases too 😁

2019-02-12 18:46 UTC, bobheadxi reviewed
looking great! just one last thing and I think we're good to go 😁

2019-02-12 18:46 UTC, bobheadxi commented on gateway/api/user/user_test.go
> +		{"internal server error", args{&request.CreateAccount{
this catches this case: https://github.com/ubclaunchpad/pinpoint/pull/125/files#diff-6f03ae89cb41aa1b937648033723e128R59

you could add a test that uses:

```go
status.Errorf(codes.Internal, ...)
```

to catch this case: https://github.com/ubclaunchpad/pinpoint/pull/125/files#diff-6f03ae89cb41aa1b937648033723e128R67

2019-02-16 20:14 UTC, closed without merging