Swagger serve api documentation ui
ubclaunchpad/pinpoint pull request #135
Opened 2019-02-18 06:00 UTC by suujia

:tickets: **Ticket(s)**: Closes #105

---

## :construction_worker: Changes

Cool UI for documentation

## :flashlight: Testing Instructions

Please run `make deps` first
```
$ make api
```
not sure why this doesn't work right now but can just run:

```
swagger serve ./swagger/swagger.yml
```
and an api will pop up in browser

2019-02-18 06:02 UTC, suujia commented
You can download the swagger.json file from the UI you served. The documentation UI can be served from both the `json` file or the `yml` file.

2019-02-18 06:04 UTC, bobheadxi requested changes

2019-02-18 06:04 UTC, bobheadxi commented on Makefile
> +api: swagger serve ./swagger/swagger.yml
I would call this `api-docs` or something, since it kinda sounds like we're running some kind of API with this command when it's just serving documentation

2019-02-18 06:04 UTC, bobheadxi commented on Makefile
> +gen: ( cd api ; swagger generate server -t gen -f ./swagger/swagger.yml -A spotter )
also this isn't how Makefiles work - the first line declares other `make` targets to run. So this command errors out like so:

```
❯ make gen
make: *** No rule to make target `(', needed by `gen'.  Stop.
```

because it's trying to run `make (` and then `make cd` and then `make api` etc.

```suggestion
gen:
    ( cd api ; swagger generate server -t gen -f ./swagger/swagger.yml -A spotter )
```

2019-02-18 06:06 UTC, bobheadxi commented
Also refer to https://github.com/ubclaunchpad/inertia/pull/571 for how to actually build a website - if you set that up and have the documentation build into the `/docs` folder of the repo, we can serve it as a website like this:

https://inertia.ubclaunchpad.com/#inertia
https://inertia.ubclaunchpad.com/api/

2019-02-18 06:08 UTC, bobheadxi commented on Makefile
> +gen: ( cd api ; swagger generate server -t gen -f ./swagger/swagger.yml -A spotter )
Also, this target is already in use, so it breaks CI: https://travis-ci.com/ubclaunchpad/pinpoint/jobs/178453301#L633

https://github.com/ubclaunchpad/pinpoint/blob/master/Makefile#L72

^^ that's also an example of how the chained Make targets work

2019-02-18 06:08 UTC, bobheadxi commented on Makefile
> +gen: ( cd api ; swagger generate server -t gen -f ./swagger/swagger.yml -A spotter )
try to follow the convention there 😄

2019-02-18 07:03 UTC, suujia commented on Makefile
> +gen: ( cd api ; swagger generate server -t gen -f ./swagger/swagger.yml -A spotter )
hehehehe good to know

2019-02-18 07:22 UTC, bobheadxi commented on Makefile
> +swagger-gen:
maybe call this `swagger` so that it's in line with the other code gen commands (`mocks`, `proto`, ...), and add it to the `gen` target like the other code gen commands (https://github.com/ubclaunchpad/pinpoint/blob/master/Makefile#L72)

*try to follow conventions*

2019-02-18 07:34 UTC, suujia commented on Makefile
> +swagger-gen:
yikes someones watching commits like a  h a w k

2019-02-18 07:34 UTC, suujia commented on Makefile
> +swagger-gen:
5 min turnaround

2019-02-18 07:52 UTC, suujia commented
kk i don't have access to configuring /docs and also is our link setup? 
serve at `https://pinpoint.ubclaunchpad.com/api` i assume?

2019-02-18 20:57 UTC, leesw98 commented on Makefile
> +## swagger: Generates API code from swagger tool
Minor point but please order these consistently

2019-02-18 22:33 UTC, bobheadxi commented
@suujia do serve at `/api`, you'll need to put the build documentation in **the folder** `/docs/api`. I'll take care of the rest - it wont be visible until this is merged into master though

2019-02-18 22:34 UTC, bobheadxi commented on Makefile
> +	@redoc-cli bundle ./docs_src/api/swagger.yml -o ./docs/api/index.html
why is there `docs-api` and `api-docs`? choose one and stick with it (swagger serve vs redoc)

2019-02-18 22:35 UTC, bobheadxi commented on Makefile
> +swagger-gen:
you still havent added the `swagger` target to `gen`

2019-02-23 21:26 UTC, zhulia96 submitted a review, later dismissed

2019-02-23 22:02 UTC, merged

2019-02-24 02:10 UTC, leesw98 commented on core/service/service_test.go
> +			args{nil, &request.Verify{Email: correctEmail, Hash: expectedHash}},
What happened here? This looks like @zhulia96's stuff

2019-02-24 03:20 UTC, bobheadxi commented on core/service/service_test.go
> +			args{nil, &request.Verify{Email: correctEmail, Hash: expectedHash}},
@suujia did some magnificent rebase - it ended up being fine in the squashed commit though