Gateway/login
ubclaunchpad/pinpoint pull request #136
Opened 2019-02-19 04:54 UTC by LynxHack

:tickets: **Ticket(s)**: Closes #

---

## :construction_worker: Changes

1. Added in cookie session to facilitate user login sessions (Universal-Cookie) in case user reloads browser
2. Fixed minor bug in retrieving user credentials at gateway from frontend side through unmarshalling which was causing crashes
3. Changed how response is passed back at the login function of index.js to prevent crashes when incorrect login
3. Moved log in functionality to higher level in react, App.js now managed loggedin state.

## :flashlight: Testing Instructions

1. Go to signup via navbar and create a new user
2. Try logging in with wrong password should result in no crashes and "incorrect login credential" being shown
3. Try logging in with correct credentials should redirect user to homepage with a navbar showing club pages
4. Can logout via logout button of navbar and delete the cookie session.

2019-02-19 05:12 UTC, bwdmonkey reviewed
LGTM for now. Will approve after testing

2019-02-19 05:12 UTC, leesw98 commented on gateway/api/user/user.go
> +	json.Unmarshal([]byte(bodyString), &info)
Is there a reason why can't do the typical json decoder process?
```golang
decoder := json.NewDecoder(r.Body)
var user request.CreateAccount
if err := decoder.Decode(&user); [...]
```

2019-02-19 05:12 UTC, leesw98 commented on frontend/src/components/App.js
> +      loggedIn: false,
I think it might be better if we keep track of the logged in user so that we can reference the user more easily.

2019-02-19 05:12 UTC, leesw98 commented on client/lib/api/index.js
> +      return response;
Is it possible to combine the two lines into one? Not familiar enough with ES6 but just curious

2019-02-19 05:12 UTC, leesw98 commented on core/database/clubuser.go
> +		return nil, errors.New("user not found")
What was the error with `2. Fixed minor bug in retrieving user credentials at gateway from frontend side through unmarshalling which was causing crashes`?

2019-02-19 05:12 UTC, leesw98 commented on core/database/clubuser.go
> +	if v.Expiry.Before(time.Now()) {
💯

2019-02-19 05:19 UTC, LynxHack commented on core/database/clubuser.go
> +		return nil, errors.New("user not found")
Previously it always crashes since for some reason the body being sent to gateway from the frontend was not being parsed properly and giving undefined. After doing unmarshalling, the body was properly parsed. Had something to do with upper and lower case in golang I think, need to look more into it, I'll try the JSON decode method again.

2019-02-19 05:32 UTC, LynxHack commented on client/lib/api/index.js
> +      return response;
ya, should be able to pass it back in one go. Good catch.

2019-02-19 06:11 UTC, bobheadxi commented on gateway/api/user/user.go
> +	json.Unmarshal([]byte(bodyString), &info)
I actually didn't know about the decoder method until a long time after i started writing Go - I think there are many places that still recommend `json.Unmarshal`. That said, `Decoder` is definitely cleaner - and we shouldn't be ignoring unmarshal/decode errors either 😉

2019-02-19 06:12 UTC, bobheadxi commented on gateway/api/user/user.go
> +	password := info.Password
I'm of the opinion that unless necessary, we should avoid doing this kind of assignment, and instead just refer directly to `info.Email`, etc.

2019-02-19 06:14 UTC, bobheadxi commented on frontend/src/components/App.js
> +      loggedIn: false,
alternatively, some kind of utility function that reads the user from the JWT

2019-02-19 06:14 UTC, bobheadxi commented on core/database/clubuser.go
> +		TableName: aws.String(clubTablePrefix + id),
why are we removing @srijonsaha 's utilities here? (looks like it might be a merge mistake?)

2019-02-19 06:16 UTC, bobheadxi commented on core/database/clubuser.go
> +		return nil, errors.New("user not found")
for json upper/lowercase issues, using the annotation tag `json:"asdf"` will take care of that

2019-02-19 06:16 UTC, bobheadxi commented on client/lib/api/index.js
> +      return response;
why are we returning the entire response, instead of just the token?

2019-02-19 06:17 UTC, bobheadxi commented on client/lib/api/index.js
> +      return response;
if the response has issues it should raise the proper exception based on the status code, so that we clearly separate response management logic in the `client` and focus on how to display things in the `frontend`

2019-02-19 06:18 UTC, bobheadxi commented on client/lib/api/index.js
> +      return response;
ie as much as possible, return only the most relevant information, in this case the `token`

2019-02-19 06:19 UTC, bobheadxi requested changes
great stuff! left a few comments throughout, some adding to @leesw98 's good feedback 🚀

2019-02-21 17:41 UTC, LynxHack commented on client/lib/api/index.js
> +      return response;
Do we not also want resp status codes? I actually modified it at the beginning since we are checking status codes at the client side for 200 before processing resp. I suppose I can make it just check for nulls of token value.

2019-02-21 18:34 UTC, bobheadxi commented on client/lib/api/index.js
> +      return response;
Yeah we don’t want to return it to the caller, since that means the caller needs to worry about status codes - abstract that away and throw informative exceptions

2019-02-21 18:35 UTC, bobheadxi commented on client/lib/api/index.js
> +      return response;
Don’t check for null token values, since if we don’t throw an exception, the value won’t be null

2019-02-21 18:36 UTC, bobheadxi commented on client/lib/api/index.js
> +      return response;
That way the flow on the front end could be:

Try -> catch -> print error

Instead of:

Try -> get status code -> 10 lines of error code logic

2019-02-23 19:19 UTC, bobheadxi commented on frontend/package.json
> +    "universal-cookie": "^3.0.7"
```suggestion
    "universal-cookie": "3.0.7"
```

2019-02-23 19:20 UTC, bobheadxi commented on gateway/api/user/user.go
> +	Email    string `json: "email"`
I don't think you're supposed to have a space here:

```suggestion
	Email    string `json:"email"`
```

https://travis-ci.com/ubclaunchpad/pinpoint/jobs/180038401#L633

2019-02-23 19:20 UTC, bobheadxi commented on frontend/src/components/App.js
> +    console.log(userToken); // temporarily bypass elint, remove once used for retrieving user data from backend
maybe put the comment on a different line, to appease the linter:

https://travis-ci.com/ubclaunchpad/pinpoint/jobs/180038402#L507

```suggestion
    // temporarily bypass elint, remove once used for retrieving user data from backend
    console.log(userToken);
```

2019-02-23 20:39 UTC, bobheadxi approved these changes
awesome 😁

2019-02-23 20:40 UTC, merged