parse different field types from JSON
ubclaunchpad/pinpoint pull request #139
Opened 2019-02-24 21:28 UTC by zhulia96

:tickets: **Ticket(s)**: Closes #123 

## :construction_worker: Changes

- make gateway parse different field types
- implemented createEvent in gateway

## :flashlight: Testing Instructions

run createEvent tests in club_test.go

2019-02-24 21:36 UTC, bobheadxi requested changes
awesome work! left some thoughts and comments. in particular, i think we should leverage the ability to define nested messages to make it clearer what messages are associated with what (since we both got very confused over "properties" vs "submissions" yesterday)

example: https://github.com/RTradeLtd/grpc/blob/master/lensv2/service.proto#L36

2019-02-24 21:36 UTC, bobheadxi commented on gateway/api/club/club.go
> +			Description: "", //TODO
you can add this to `CreateEvent` to require it in request body

2019-02-24 21:36 UTC, bobheadxi commented on gateway/schema/event.go
> +	// Properties is one of protobuf ...
maybe specify where exactly the protobuf definitions are?

2019-02-24 21:36 UTC, bobheadxi commented on protobuf/models/models.proto
> +message LongTextProps { }
maybe we should put a `maxLen` property here

2019-02-24 21:36 UTC, bobheadxi commented on protobuf/request/request.proto
> +  models.FieldProps fields = 1;
let's remove this for now to avoid confusion (this won't be `FieldProps`, maybe more like `Field` or `EventField`)

2019-02-24 21:36 UTC, bobheadxi commented on protobuf/models/models.proto
>    };
you can define props here actually, to make the scopes clearer, ie:

```suggestion
  };
  
  message LongText { }
  message ShortText { }
```

these will then be generated as:

```
FieldProps_LongText
```

2019-02-24 21:36 UTC, bobheadxi commented on protobuf/models/models.proto
> +message FieldProps {
let's rename this `Event_FieldProps`? or define it *inside* `EventProps` as `Field` like I described in the other comment

2019-02-25 02:35 UTC, bwdmonkey requested changes

2019-02-25 02:35 UTC, leesw98 commented on core/service/service.go
> +	// TODO
💯

2019-02-25 02:35 UTC, leesw98 commented on gateway/api/club/club_test.go
> +		{"bad input", args{"/my_club/period/my_period/event/create", nil}, http.StatusBadRequest},
By `"bad input"`, is it supposed to mean `"bad param"` if so can you please change this? It's easier to understand the term "param" in this context.

2019-02-25 02:35 UTC, leesw98 commented on protobuf/models/models.proto
> +message LongTextProps { }
We can probably allow arbitrary length with long text and just set short text to 256 char or something.

2019-02-25 02:40 UTC, bobheadxi commented on protobuf/models/models.proto
> +message LongTextProps { }
i still think we should allow a configurable length - wanting ~200 words, ~500words, etc is something you see pretty often

2019-02-25 02:40 UTC, leesw98 commented on protobuf/models/models.proto
> +message LongTextProps { }
Semi-relevant: `The length of a string must be greater than zero and is constrained by the maximum DynamoDB item size limit of 400 KB`

2019-02-25 02:42 UTC, leesw98 commented on protobuf/models/models.proto
> +message LongTextProps { }
Oh yes. Good idea.

2019-02-25 18:20 UTC, zhulia96 commented on protobuf/models/models.proto
> +message FieldProps {
I'll define it insode EventProps because I think that's less confusing

2019-02-25 19:33 UTC, bwdmonkey submitted a review, later dismissed

2019-02-25 19:33 UTC, leesw98 commented on protobuf/models/models.proto
> +      string maxLen = 1;
I believe these are meant to be `int` for allowing the club owners to set max text length.

2019-02-25 20:03 UTC, bobheadxi commented on protobuf/models/models.proto
> +      string maxLen = 1;
Also maybe follow the conversion of snake_case (see the other variables)

2019-02-27 22:37 UTC, bobheadxi commented on protobuf/pinpoint.proto
> +import "protobuf/response/response.proto";
I'm pretty sure this change breaks the compiler:

```
~/go/src/github.com/ubclaunchpad/pinpoint gateway/123-event-request-schema
❯ make proto                                   
protoc -I protobuf pinpoint.proto --go_out=plugins=grpc:protobuf
protobuf/request/request.proto: File not found.
protobuf/response/response.proto: File not found.
pinpoint.proto: Import "protobuf/request/request.proto" was not found or had errors.
pinpoint.proto: Import "protobuf/response/response.proto" was not found or had errors.
pinpoint.proto:10:17: "request.Status" is not defined.
pinpoint.proto:10:42: "response.Status" is not defined.
pinpoint.proto:11:17: "request.Empty" is not defined.
pinpoint.proto:11:41: "response.Empty" is not defined.
pinpoint.proto:14:19: "request.CreateEvent" is not defined.
pinpoint.proto:14:49: "response.Message" is not defined.
pinpoint.proto:17:21: "request.CreateAccount" is not defined.
pinpoint.proto:17:53: "response.Message" is not defined.
pinpoint.proto:18:14: "request.Verify" is not defined.
pinpoint.proto:18:39: "response.Message" is not defined.
pinpoint.proto:19:13: "request.Login" is not defined.
pinpoint.proto:19:37: "response.Message" is not defined.
make: *** [proto] Error 1
```

2019-02-27 22:37 UTC, bobheadxi commented on protobuf/pinpoint.proto
> +import "protobuf/response/response.proto";
it should be:

```suggestion
import "response/response.proto";
```

as before

2019-02-27 23:50 UTC, bobheadxi commented on protobuf/models/models.proto
> +      int32 max_len = 1;
I don’t think this needs a max len

Also for long text, 64 bit max Len seems overkill haha

2019-02-28 00:50 UTC, bobheadxi commented
@zhulia96 need to update the generated code 😋

2019-02-28 01:06 UTC, leesw98 commented on protobuf/models/models.proto
> +    string name = 1;
If so, I believe we can grab the type via `fieldProps.Properties.(type)` so it may be redundant to have this.

2019-02-28 01:10 UTC, bobheadxi commented on gateway/api/club/club.go
> +			EventID:     data.EventID,
I think the general consensus re: discussions around #61 eventually settled on "generated ID's dont play too well with how DynamoDB querying works".

I think most of the discussions were with @srijonsaha who might be able to confirm, if that's the case we might as well kill generated IDs now and close #61 , and we can let this be a un-special-characterd version of `Name`. For example:

```
Name: Spring 2019 Recruitment
EventID: spring_2019_recruitment
```

that would be a TODO for another PR though, so don't worry too much about it yet @zhulia96 😋

2019-02-28 01:12 UTC, bobheadxi commented on protobuf/models/models.proto
> +    string name = 1;
I think it actually is the name of the field. For example, `name: "resume link"` or `name: "why do you want to join"`

2019-02-28 01:37 UTC, leesw98 commented on gateway/api/club/club.go
> +			EventID:     data.EventID,
Hmm okay. Sounds good for now. 👍

2019-02-28 01:38 UTC, bwdmonkey reviewed
LGTM besides `make gen`. Well done 👍 Will approve afterward.

2019-02-28 02:31 UTC, bobheadxi approved these changes

2019-02-28 02:31 UTC, bobheadxi commented
Awesome work!

2019-02-28 02:33 UTC, bwdmonkey approved these changes
LGTM 💯

2019-02-28 02:34 UTC, merged