Add tests for event application
ubclaunchpad/pinpoint pull request #144
Opened 2019-03-04 04:30 UTC by suujia

:tickets: **Ticket(s)**: Closes #89

---

## :construction_worker: Changes

A brief summary of what changes were introduced.

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.

2019-03-04 04:54 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +		// getEvents bool
```suggestion
```

2019-03-04 04:54 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			// }
whats this doing here

2019-03-04 05:01 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			// _, err = db.GetEvents(tt.args.clubID, tt.args.period)
what do you mean how to relate a club to a period? the signature here:

```go
func (db *Database) GetEvents(clubID string, period string) ([]*models.EventProps, error) 
```

is almost exactly the same as the signature in `GetEvent` which you seem to have successfully tested:

```go
func (db *Database) GetEvent(clubID string, period string, eventID string) (*models.EventProps, error)
```

shouldnt `GetEvents` as you wrote here be the same?

2019-03-04 05:03 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			_, err := db.GetApplicant(tt.args.clubID, tt.args.applicant.Period, tt.args.applicant.Email)
we should probably check if the applicant we get is actually the applicant we are looking for, instead of discarding the return

2019-03-04 05:04 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			_, err = db.GetApplicants(tt.args.clubID, tt.args.applicant.Period)
same here - in this particular test, there should be only one applicant, so you can check if `len(applicants) > 0` and if the first applicant is the applicant we want

2019-03-04 05:04 UTC, bobheadxi requested changes

2019-03-04 05:04 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			_, err := db.GetApplication(tt.args.clubID, tt.args.application.Period, tt.args.application.EventID, tt.args.application.Email)
same here, we should check if the application we get is the application we want

2019-03-04 05:04 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			_, err = db.GetApplications(tt.args.clubID, tt.args.application.Period, tt.args.application.EventID)
and here

2019-03-04 05:04 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +			_, err := db.GetTags(tt.args.clubID, tt.args.tag.Period)
and here

2019-03-04 05:59 UTC, bwdmonkey reviewed
Not much to add on top of @bobheadxi's comments. Follow his comments 🙂

2019-03-04 05:59 UTC, leesw98 commented on core/database/eventapplicant_test.go
> +				t.Errorf("Database.AddNewEvent() error = %v, wantErr %v", err, tt.err.addEvent)
Sidenote: I think it might be useful to add which `tt.args` failed in the `t.Errorf` prints. @bobheadxi Thoughts?

2019-03-04 05:59 UTC, leesw98 commented on core/database/eventapplicant_test.go
> +			_, err = db.GetApplicants(tt.args.clubID, tt.args.applicant.Period)
In this case, we should check if `len() == 1`

2019-03-04 05:59 UTC, leesw98 commented on core/database/eventapplicant_test.go
> +		// getEvents bool
Keep this alive and just add the test for `getEvents`

2019-03-04 06:00 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +				t.Errorf("Database.AddNewEvent() error = %v, wantErr %v", err, tt.err.addEvent)
the testing library logs `tt.args.name`, which ideally should be sufficient to tell you what args failed.

2019-03-04 06:02 UTC, bobheadxi commented on core/database/eventapplicant_test.go
> +		// getEvents bool
i accidentally deleted a comment here by myself and @leesw98 , but this should be fixed instead of my removed re: https://github.com/ubclaunchpad/pinpoint/pull/144/files#r261923079

2019-03-10 07:40 UTC, bobheadxi commented
@suujia the failing test: https://travis-ci.com/ubclaunchpad/pinpoint/jobs/183612664#L1830

you might want to pull in #152 to make things easier to debug

2019-03-29 09:00 UTC, bobheadxi commented on core/database/eventapplicant.go
> +				S: aws.String(eventPrefix),
👁

2019-03-29 09:00 UTC, bobheadxi approved these changes

2019-03-29 09:00 UTC, merged