Core/g rpc auth
ubclaunchpad/pinpoint pull request #54
Opened 2018-10-15 00:32 UTC by LynxHack

:tickets: **Ticket(s)**: Closes #

---

## :construction_worker: Changes

A brief summary of what changes were introduced.

Mutual authentication between Gateway and Core is created via context from metadata.
A test case gRPC ping is created to be ran at the beginning of the connection.

Upon starting up both core and gateway, the gateway first pings the core with a token. The core check if the token is valid (otherwise terminates connection). Afterwards, the core also sends back a metadata header containing its token to be validated on the gateway side.

## :flashlight: Testing Instructions
Run in separate terminals to see successful connection
make core
make gateway

Open up  ./gateway/api.go    && ./core/service/service.go
and change the value of token being sent 

(service.go's SayHello response function)
or
(api.go's  md metadata pair value in the Run function)

Run in separate terminals to see unsuccessful connection
make core
make gateway

2018-10-15 00:50 UTC, bobheadxi commented on protobuf/pinpoint.proto
> +  rpc SayHello(PingMessage) returns (PingMessage) {}
I don't think we need a new RPC here - just use `GetStatus()` for now

2018-10-15 00:51 UTC, bobheadxi commented on core/service/service.go
> +func AuthUnaryInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
This can probably go in a separate file in `service`, such as `middleware.go`. Additionally, since this doesn't get used outside the `service` pacakge we can probably make it private

2018-10-15 00:52 UTC, bobheadxi commented on core/service/service.go
> +		return nil, grpc.Errorf(codes.Unauthenticated, "missing context metadata")
ooh TIL grpc has its own error packages with error codes, thats pretty slick

2018-10-15 00:55 UTC, bobheadxi commented on protobuf/pinpoint.proto
> +  rpc SayHello(PingMessage) returns (PingMessage) {}
Ah wait sorry I misunderstood - this is purely for establishing connection. Perhaps `Handshake()` or `Verify()` would convey this better. Also, instead of `PingMessage` maybe use `request.Empty` and `response.Empty` (speaking of which, it is good practice to have separate request/response types, and also to keep this organized we should keep our requests and response definitions outside this file, which should be used to devine `service Core` only)

2018-10-15 00:55 UTC, bobheadxi commented on core/service/service.go
> +			AuthUnaryInterceptor,
Nice!

2018-10-15 00:55 UTC, LynxHack commented on protobuf/pinpoint.proto
> +  rpc SayHello(PingMessage) returns (PingMessage) {}
I agree, I'll change that. Just wanted to explore with protobuf a little.

2018-10-15 00:57 UTC, bobheadxi commented on core/service/service.go
> +	log.Printf("Receive message %s", in.Greeting)
we have a dedicated logger, `s.l`, and using it will help keep our logs organized in one place - in this case, you might write:

```go
s.l.Info("received message",
  "greeting", in.Greeting)
```

which would output something like:

```
{"level":"info",message":"received message","greeting":"..."}
```

there are examples of how to use this logger throughout the code, take a quick look at those as a reference point :)

2018-10-15 00:59 UTC, bobheadxi commented on gateway/api/api.go
> +	md := metadata.Pairs("token", "valid-token")
this token should be retrieved from `os.Getenv()` (environment variables) instead. for example, `os.Getenv("PINPOINT_CORE_TOKEN")`, and then:

```sh
env PINPOINT_CORE_TOKEN=valid_token make api
```

2018-10-15 01:00 UTC, LynxHack commented on core/service/service.go
> +	log.Printf("Receive message %s", in.Greeting)
Sounds good, I'll add in the logger!

2018-10-15 01:01 UTC, bobheadxi commented on core/service/service.go
> +	grpc.SendHeader(ctx, metadata.New(map[string]string{"coretoken": "valid-coretoken"}))
this should be in an environment variable as well

2018-10-15 01:03 UTC, bobheadxi commented on gateway/api/api.go
> +	// Ping Communication with Core to Authentication First
this isn't the simplest procedure out there, and having this here clutters up the startup logic - it might be good to have the handshake occur in a helper function, `api.EstablishConnection()` for example

2018-10-15 01:04 UTC, bobheadxi commented on gateway/api/api.go
> +		if value[0] == "valid-coretoken" {
this should be in environment too

2018-10-15 01:08 UTC, LynxHack commented on gateway/api/api.go
> +	md := metadata.Pairs("token", "valid-token")
ohhhh I see, I was actually wondering where the .env in th dev folder went.

2018-10-15 01:08 UTC, LynxHack commented on gateway/api/api.go
> +	md := metadata.Pairs("token", "valid-token")
Sounds good!

2018-10-15 01:08 UTC, bobheadxi requested changes
This is a good start! Most of my comments are related to making things clearer or improving organization, but for now short string-based tokens should be more than adequate. Further down the line we might want some more secure key-generation and verification strategies, but that's a problem for another day 😁 

One general comment: it's not immediately clear who is using what token. It appears to me that there are 2 tokens:

- a connect token, which `gateway` sends to `core`, and `core` verifies it against its own expectations
- a verification token, which `core` sends back to `gateway`, and `gateway` verifies it against its own expectations

Does that sound right @LynxHack ? It might become a bit clearer once they have both been moved into environment variables.

Thanks for the PR! 🎉

2018-10-15 01:09 UTC, bobheadxi commented on gateway/api/api.go
> +	md := metadata.Pairs("token", "valid-token")
Oh yeah I've removed the `.env` in #39 since @Rahman2600 was having troubles loading it. For now, secrets and tokens and whatnot should be the only thing passed in via env, and those can be declared inline as per the example above 👍

2018-10-15 19:34 UTC, bobheadxi commented
@LynxHack I feel there might be confusing conflicts after #52 and #55 gets merged - focus on cleaning up this branch as is (don't merge anything from other branches), and we can sort out any conflicts this saturday 💯

2018-10-15 19:55 UTC, LynxHack commented
Sounds good, I won't be able to clean this up until later on this week after I finish my midterm. But I'll have them implemented probably on Friday.

2018-10-20 09:50 UTC, bobheadxi reviewed
2:30am commits 😅 good work! left a few increasingly nitpicky comments

2018-10-20 09:50 UTC, bobheadxi commented on core/service/middleware.go
> +func authUnaryInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
Nice!

2018-10-20 09:50 UTC, bobheadxi commented on core/service/service.go
> +	// grpc.SendHeader(ctx, metadata.New(map[string]string{"coretoken": "invalid-coretoken"}))
can probably remove this unused code for now. also, the docstring reads `SayHello` for a `Handshake` function (also this is super nitpick but `Handshake` is one word instead of `HandShake` 😋 )

2018-10-20 09:50 UTC, bobheadxi commented on core/service/service.go
> +	// grpc.SendHeader(ctx, metadata.New(map[string]string{"coretoken": "invalid-coretoken"}))
https://en.wikipedia.org/wiki/Handshaking

2018-10-20 09:50 UTC, bobheadxi commented on gateway/api/api.go
> +	// Ping Communication with Core to Authentication First
`authenticate with core first`

also, there's some commented code a few lines above this that can be removed

2018-10-20 09:50 UTC, bobheadxi commented on gateway/api/api.go
> -		return errors.New("invalid host and port configuration provided")
why was this removed?

2018-10-20 09:50 UTC, bobheadxi commented on gateway/api/api.go
> +	if err := a.establishConnection(); err != nil {
clean 😁

2018-10-20 17:04 UTC, LynxHack commented on gateway/api/api.go
> -		return errors.New("invalid host and port configuration provided")
whoops!

2018-10-23 18:55 UTC, bobheadxi reviewed
@LynxHack  Remember to tag this as `ready for review` when you're done 😄

2018-10-23 18:55 UTC, bobheadxi commented on Makefile
> +	env PINPOINT_CORE_TOKEN=valid_token PINPOINT_GATEWAY_TOKEN=valid_token
try `export` here and in the other command

2018-10-23 18:55 UTC, bobheadxi commented on gateway/utils/utils.go
> +	return ctxnew
just for the sake of brevity you could just return `ctxnew` inline:

```
...
return metadata.NewOutgoingContext(ctx, md)
```

2018-10-23 18:56 UTC, bobheadxi commented
@LynxHack It looks like you need to run `make proto` to update the protobuf API:

https://travis-ci.com/ubclaunchpad/pinpoint/jobs/153158192

2018-10-23 19:18 UTC, bobheadxi commented on Makefile
> +	export env PINPOINT_CORE_TOKEN=valid_token PINPOINT_GATEWAY_TOKEN=valid_token
haha sorry i meant `export` *instead of* `env` :p

2018-10-23 19:19 UTC, LynxHack commented on Makefile
> +	export env PINPOINT_CORE_TOKEN=valid_token PINPOINT_GATEWAY_TOKEN=valid_token
man, you are too fast!

2018-10-26 16:28 UTC, bobheadxi reviewed
left a comment about why I think tests are failing on Travis. Also, looks like you updated the grpc API but travis is still detecting some diffs - might be a version mismatch on your end or something else. Don't worry about that for now, we can address that specific issue tomorrow 😁 

good work!

2018-10-26 16:28 UTC, bobheadxi commented on gateway/api/api_test.go
> +			a.l.Infow("connecting to core",
don't use the logger in tests - use `t.Log()`

2018-10-26 16:28 UTC, bobheadxi commented on gateway/api/api_test.go
> +			// opts := tt.args.opts
unused 😢

2018-10-26 16:28 UTC, bobheadxi commented on gateway/api/api_test.go
> +		errorexpected bool
lets keep this as `wantErr` for brevity and consistency with the other tests

2018-10-26 16:28 UTC, bobheadxi commented on gateway/api/api_test.go
> +		{"Token Inserted", gateutil.SecureContext(context.Background()), testopts, false},
good test cases!

2018-10-26 16:28 UTC, bobheadxi commented on gateway/api/api_test.go
> +			if err := a.establishConnection(tt.ctx); err != nil {
I think this fails because in tests, `core` is not online in travis. We could start up core before tests start using the `make` script, but we'll have to make sure none of the `core` startup tests use the same port (should be pretty trivial to avoid). Hope that makes sense!

2018-10-26 17:31 UTC, bobheadxi commented on gateway/api/api_test.go
> +			if err := a.establishConnection(tt.ctx); err != nil {
Actually, I think we shouldn’t test this by runnin core at all

2018-10-26 17:32 UTC, bobheadxi commented on gateway/api/api_test.go
> +			if err := a.establishConnection(tt.ctx); err != nil {
We should test each behaviour in isolation - for example, test the server handshake by calling the endpoint as a function in core

For gateway, test the context constructors but don’t actulaly establish connections.

2018-10-26 17:32 UTC, bobheadxi commented on gateway/api/api_test.go
> +			if err := a.establishConnection(tt.ctx); err != nil {
It means we lose some coverage in gateway, but this is better until @suujia finishes her task of adding the ability to mock the client.

2018-10-29 05:44 UTC, bobheadxi commented
@LynxHack for clientside, have you looked at this? https://godoc.org/google.golang.org/grpc#WithPerRPCCredentials

2018-11-03 19:46 UTC, bobheadxi commented
Im gonna work on making travis pass

2018-11-05 02:03 UTC, bobheadxi approved these changes

2018-11-05 02:07 UTC, merged