Frontend/login reset
ubclaunchpad/pinpoint pull request #72
Opened 2018-11-03 23:47 UTC by LynxHack

:tickets: **Ticket(s)**: Closes #

---

## :construction_worker: Changes

A brief summary of what changes were introduced.

Created Login and reset pages. Button should send axios request to backend. This will be implemented after endpoints are set up.

## :flashlight: Testing Instructions

Explain how to test your changes, if applicable.

Look and marvel.

2018-11-04 06:33 UTC, bobheadxi requested changes
I love it, super faithful to the mockup 🥇 

Talked to you a little about leveraging the utils SCSS setup to reduce component-specific styles, give that a try and we can probably merge this once we reduce the custom styles a little 😁 

Thanks!

2018-11-04 06:33 UTC, bobheadxi commented on .travis.yml
> +        - TEST="frontend" CI=false
hehehhee 
now that I think about it - can you add a comment here documenting why we added this (allow CI to pass despite linter warnings), and that at some point we should remove this workaround?

2018-11-04 06:33 UTC, bobheadxi commented on frontend/src/styles/components/reset.scss
> +}
https://stackoverflow.com/questions/44704968/visual-studio-code-insert-new-line-at-the-end-of-files 😉

2018-11-09 20:19 UTC, bobheadxi requested changes
looking good! just a few small fixes and I think we can merge this for now 😁

2018-11-09 20:19 UTC, bobheadxi commented on frontend/src/styles/utils/flex.scss
> +  &-inline{ display: inline-flex }
why remove the space here 😢

2018-11-09 20:19 UTC, bobheadxi commented on frontend/src/styles/utils/spacing.scss
> +    margin-bottom: $spacing-xs;
margin-top, margin-bottom are the same - this could probably be a generic margin class like this:

```scss
  // top margin
  &-top, &-ends {
    &-xs { margin-top: $spacing-xs }
  }

  // bottom margin
  &-bot, &-ends {
    &-xs { margin-bottom: $spacing-xs }
  }
```

usage:

```
margin-ends-xs
```

2018-11-09 20:19 UTC, bobheadxi commented on frontend/src/components/Login.js
> +        <button className="click-button button-small animate-button magin-form" type="submit" onClick={this.attemptLogin}>Sign in</button>
I think you mean `margin`, not `magin`?

2018-11-09 20:19 UTC, bobheadxi commented on frontend/src/components/Login.js
> +        <button className="click-button button-small animate-button magin-form" type="submit" onClick={this.attemptLogin}>Sign in</button>
oh shit jk this was my bad - can you change this for me? (magin -> margin) 😅 

https://github.com/ubclaunchpad/pinpoint/blob/56da798eea797d2d8a859a61fabc090074b94dc7/frontend/src/styles/utils/spacing.scss#L42

2018-11-09 20:34 UTC, LynxHack commented on frontend/src/styles/utils/spacing.scss
> +    margin-bottom: $spacing-xs;
oh wait, I just saw this, ya, I can throw it into -xs subclass

2018-11-09 20:34 UTC, bobheadxi commented on frontend/src/styles/utils/spacing.scss
> +    &-m { margin-top: $spacing-xs }
its probably clearer to match the names here with the spacing class used - in this case, `-xs` instead of `-m`

2018-11-09 20:37 UTC, LynxHack commented
For some strange reason though codegen still fails. This branch doesn't have any proto rebuilds since it's just a fresh merge pull from master + frontend changes.

2018-11-09 20:45 UTC, bobheadxi commented
@LynxHack try to update to go protoc plugin:

```
go get -u github.com/golang/protobuf/protoc-gen-go
```

ill look into resolving the silent protoc-gen-go updates at some point

2018-11-09 21:41 UTC, bobheadxi approved these changes
Awesome work!

2018-11-09 21:42 UTC, merged