added tag model
ubclaunchpad/pinpoint pull request #79
Opened 2018-11-10 13:44 UTC by adesouky

:tickets: **Ticket(s)**: Closes #49 

---

## :construction_worker: Changes

Added tag models and create, get, delete, and change name operations

## :flashlight: Testing Instructions

go to core/database and run "go test -run TestTag"

2018-11-10 13:49 UTC, bobheadxi reviewed
wow thanks for getting this PR in! 😍 

first of all, make sure you have a `gofmt` plugin installed on your IDE - I recommend using [Visual Studio Code](https://code.visualstudio.com/) alongside the [official Go plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go)

it'll help you fix a lot of common errors (at a glance I see a few) and help keep our code consistent!

2018-11-10 13:55 UTC, adesouky commented
Yea that sounds so helpful ill definitely use it.
Upon testing, I found that the change name test is inconsistent. 
Although the update operation goes through, the name change is not consistent. i.e it will change the name on one test run, but not on the following. I have no idea why though!

2018-11-10 13:56 UTC, bobheadxi commented
@adesouky hm interesting...

although on that front, I think there might have been a slight misunderstanding - there shouldn't be a need for a name change function, just the ability to add and remove tags from an applicant

we can clarify this tomorrow, get some rest! 😁

2018-11-10 14:00 UTC, adesouky commented
Well good to know 😂

2018-11-11 19:42 UTC, bobheadxi requested changes
Awesome work! 🎉  See if you can model the tests after the new tests the way we talked about them yesterday! Great use of the `go test -run TestTag` suggestion as well

I think @srijonsaha should have a look at this too before we land this PR

Thanks! 😁

2018-11-11 19:42 UTC, bobheadxi commented on core/database/tag.go
> +				S: aws.String(t.ApplicantID),
nice! I think you can probably put this on one line, like so:

```
"pk": { S: ... },
```

less roomy and easier to read imo

2018-11-11 19:42 UTC, bobheadxi commented on core/database/tag.go
> +		Item: map[string]*dynamodb.AttributeValue{
@srijonsaha might have thoughts on this, but I think for applicant attributes for tags, it might be easier if we enforce that every entry must have a `type` field

```
pk: ...
sk: ...
tag_name: ...
type: tag
```

this type field doesnt have to be on the struct itself, just here when we insert into dynamodb. that way when we pull all the data, we know how to parse each item

2018-11-11 19:42 UTC, bobheadxi commented on core/database/database_test.go
> +func TestTag(t *testing.T) {
these tests are okay, but remember what we talked about yesterday and try to model these tests after the new tests! For example:

https://github.com/ubclaunchpad/pinpoint/blob/master/core/database/clubuser_test.go#L11

Also, in Go, `/* ... */` comments are rarely used - if you want to add a comment just use `//`

2018-11-11 19:42 UTC, bobheadxi commented on core/database/database_test.go
> +	//"time"
i think this can be removed

2018-11-11 19:43 UTC, bobheadxi commented
Oh yeah and don't worry about the merge conflicts too much - I can handle them for you before you merge if you want (but I recommend you give it a try locally! just run `git pull origin master`)

2018-11-11 23:50 UTC, adesouky commented on core/database/tag.go
> +		Item: map[string]*dynamodb.AttributeValue{
hmm.. I don't get what that would be used for as tags are in a separate table all together.

2018-11-11 23:51 UTC, adesouky commented on core/database/database_test.go
> +func TestTag(t *testing.T) {
Will do that!

2018-11-12 00:54 UTC, bobheadxi commented on core/database/tag.go
> +		Item: map[string]*dynamodb.AttributeValue{
the tags will be in the same table alongside `events`, and other datatypes that we might want to include

2018-11-12 00:55 UTC, bobheadxi commented on core/database/tag.go
> +		TableName: aws.String("TagTable"),
ah I see what you mean now with your other comment - this should be a club table, see #64

2018-11-12 01:31 UTC, adesouky commented on core/database/tag.go
> +		TableName: aws.String("TagTable"),
Yea that makes much more sense!

2018-11-12 01:37 UTC, adesouky commented on core/database/tag.go
> +		TableName: aws.String("TagTable"),
So the Tag operations should take the club(or the clubID) they are adding to as a parameter?

2018-11-12 01:46 UTC, bobheadxi commented on core/database/tag.go
> +		TableName: aws.String("TagTable"),
yep! I think the clubs are keyed by name

2018-11-12 07:08 UTC, srijonsaha commented on core/database/tag.go
> +		Item: map[string]*dynamodb.AttributeValue{
this is for the applicant specific tags and not for the event templates right? then this stuff should go inside the clubtable not a separate new tag table. also since I'm working on how the clubtable is gonna be like and models in there it might better to hold off on this till my changes are in?

2018-11-12 07:21 UTC, srijonsaha commented
another thing you could do is just submit this change and I can work off this commit and integrate it will the clubtable

2018-11-12 07:39 UTC, bobheadxi commented
> another thing you could do is just submit this change and I can work off this commit and integrate it will the clubtable

I'll leave this up to @adesouky ! Anas, just add the "Ready for Review" label back to this PR when you've addressed the comments regarding the tests and the code cleanup (comments, etc.) - up to you if you want to add the changes for integrating with the club table - and I'll fix up the merge conflicts and we can merge this 😁

2018-11-21 19:12 UTC, bobheadxi reviewed
Awesome work cleaning this up @adesouky ! 😍 

Left one super minor comment regarding naming - once that's fixed, I think we're good to merge this 😁

2018-11-21 19:12 UTC, bobheadxi commented on core/database/tag.go
> +func (db *Database) GetTag(ApplicantID string, PeriodID string, EventID string, c *model.Club) (*model.Tag, error) {
in Go, variable names should be lowercased, as uppercased names have a special meaning in a lot of contexts (exports)

```suggestion
func (db *Database) GetTag(applicantID string, periodID string, eventID string, c *model.Club) (*model.Tag, error) {
```

2018-11-21 19:12 UTC, bobheadxi commented on core/database/tag_test.go
> +				Description: "1337 h4x0r",
😉

2018-11-21 19:12 UTC, bobheadxi commented on core/model/tag.go
> +// Tag model
succinct, but it works 😅

2018-11-22 01:07 UTC, adesouky commented on core/database/tag.go
> +func (db *Database) GetTag(ApplicantID string, PeriodID string, EventID string, c *model.Club) (*model.Tag, error) {
fixed it!

2018-11-22 02:33 UTC, bobheadxi approved these changes
great stuff, thanks @adesouky !

2018-11-22 02:33 UTC, bobheadxi commented
@ubclaunchpad/pinpoint as always, please take a look when yall have a chance

2018-11-22 02:33 UTC, merged